### ISSUE TITLE
USER STORY: To join waiting list

### ISSUE THREAD

**Issue by email2ify** [email2ify/Yoga#2]
As a **Site User** I can **join the waiting list** so that I can **participate in the next meeting programme**

## Acceptance Criteria:

- **Acceptance Criteria 1**: The site should have a waiting list box or field to join the list and a community section

## Tasks:

- [ ] Design user interface for the site
- [ ] Create HTML,CSS and JAVASCRIPT
- [ ] Create a field in the model to track the email addresses
- [ ] Test the functionality
