### ISSUE TITLE
USER STORY: Admin accessing the waiting List

### ISSUE THREAD

**Issue by email2ify** [email2ify/Yoga#3]
As a **Site User / Admin** I can **view the waiting list email addresses post** so that **I can see registered email addresses in turns for the next meeting programme**

## Criteria:

- **Criteria 1**: The admin should be able to modify and approve registered email addresses/names from the database
- **Criteria 1**: In order to collect users feedback, as an administrator, I can publish a post

## Tasks:

- [ ] Using postgres to the Database
- [ ] Create HTML,CSS, JAVASCRIPT and PYTHON
- [ ] Create a field in the model to track the email addresses in the database
- [ ] Test the functionality
