### ISSUE TITLE
USER STORY: Register an account

### ISSUE THREAD

**Issue by email2ify** [email2ify/Yoga#4]
As a **Site User** I can **register an account** so that I can **comment or testify**

## Acceptance Criteria:

- **Acceptance Criteria 1**: The site should be able to enter user name to create an account.
- **Acceptance Criteria 1**:  After submitting, the default submission confirmation should be adjusted to include the user name(not sure of this function)

## Tasks:

- [ ] Design user interface for the site
- [ ] Create HTML,CSS and JAVASCRIPT
- [ ] Create a field in the model to track the username
- [ ] Test the functionality
