### ISSUE TITLE
USER STORY: Creating and deleting post

### ISSUE THREAD

**Issue by email2ify** [email2ify/Yoga#5]
As a **Site User/ Admin** I can **create, read, update and delete post from the comment section and registered email address** so that **I can easily edit messages and also be able to manage registered  email address/names**

## Acceptance Criteria:

- **Acceptance Criteria 1**: The site should should be able to create, read, update, and delete post and a community section

## Tasks:

- [ ] Design user interface for the site
- [ ] Create HTML,CSS,JAVASCRIPT and PYTHON 
- [ ] Create a field in the model to track post and email addresses
- [ ] Test the functionality
