### ISSUE TITLE
USER STORY: Approving and disapproving comments

### ISSUE THREAD

**Issue by email2ify** [email2ify/Yoga#6]
As a **Site Admin** I can **approve or disapprove comments or testify before publishing** so that **I can filter out objectionable comments or testifying messages**

## Criteria:

- **Criteria 1**: After submitting post or comment , the confirmation should be able to filter out if or not the content will be displayed

## Tasks:

- [ ] Update the admin module view
- [ ] Update controller function
- [ ] Test the functionality
